version: "3.3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.local
    container_name: agendanet-schedule
    env_file:
      - .env
    ports:
      - "8090:8090"
    volumes:
      - ./:/var/www/app
    links:
      - db

  db:
    container_name: mysql8
    image: mysql:8.0
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: agendanet_schedule
    ports:
      - '3307:3306'