version: "3.3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.local
    container_name: agendanet-schedule
    env_file:
      - .env
    ports:
      - "8090:8090"
    volumes:
      - ./:/var/www/app
