name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag jonathanfvb/bref:$(date +%s) --build-arg AWS_KEY=${{ secrets.JHOU_AWS_KEY }} --build-arg AWS_SECRET=${{ secrets.JHOU_AWS_SECRET }}
